movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'
urlpatterns = [

    path('',views.index, name='index'),
    path('movie/<int:movie_id>',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),

]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=250)
    des=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/moviesapp/models.py
from django.db import models

# Create your models here.

movieproject/movieapp/forms.py
from django import forms
from . models import movie
class MovieForm(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','des','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import movie
from .forms import MovieForm
# Create your views here.
def index(request):
    movies=movie.objects.all()
    context={
        'movie_list':movies
    }
    return render(request,'index.html',context)

def detail(request,movie_id):
    x=movie.objects.get(id=movie_id)

    return render(request,"detail.html",{'movie':x})
def add_movie(request):
    if request.method=='POST':

        name=request.POST.get('name')
        des = request.POST.get('des')
        year = request.POST.get('year')
        img = request.FILES['img']
        movies=movie(name=name,des=des,year=year,img=img)
        movies.save()

    return render(request,'add.html')

def update(request,id):
    movies=movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movies)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method =='POST':
        movies=movie.objects.get(id=id)
        movies.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/moviesapp/views.py
from django.shortcuts import render

# Create your views here.

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter movie name">
    <br>
    <input type="text" name="des" placeholder="enter movie description">
    <br>
    <input type="text" name="year" placeholder="enter movie year">
    <br>
    <input type="file" name="img">
    <br>
    <input type="submit">

</form>
{% endblock %}

movieproject/templates/add_movie.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter movie name">
    <br>
    <input type="text" name="des" placeholder="enter movie description">
    <br>
    <input type="text" name="year" placeholder="enter movie year">
    <br>
    <input type="file" name="img">
    <br>
    <input type="submit">

</form>
{% endblock %}

movieproject/templates/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">


</head>

<body>
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">

    <h3>online movie store</h3>
      <a href="/add">Add movie</a>
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="POST">
  {% csrf_token %}
  Are sure to delete this movie?
  <input type="submit">
</form>

movieproject/templates/detail.html
{%extends 'base.html'%}
{% block body%}
<div class="container">
    <div class="row">
        <div class="col-md-6">
           <img src="{{movie.img.url}}" width="300" height="300" style="padding:20px;">
        </div>
        <div class="col-md-6" style="padding:10px;">
            <h2>{{movie.name}}</h2>
            <h3>{{movie.year}}</h3>
            <h4>{{movie.des}}</h4>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a>
        </div>
    </div>

</div>






{%endblock%}

movieproject/templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}


<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3" style="padding:20px;">
          <div class="card">
             <img class="card-img-top" src="{{i.img.url}}" alt=""  height="250">
                 <div class="card-body">
                   <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text">{{i.des}}</p>
                     <h6 class="card-title">{{i.year}}</h6>
                    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">View details</a>
                 </div>
          </div>

        </div>
        {% endfor %}
    </div>
</div>




{%endblock%}